from __future__ import annotations

from typing import Any

import torch

from mini_grin_rebuild.core.configs import SimulationConfig, TrainingConfig
from mini_grin_rebuild.physics.layer import DifferentiableGradientLayer


def freeze_forward_model(model: torch.nn.Module) -> None:
    """Freeze a differentiable forward model for fixed-physics losses / QC."""

    if isinstance(model, DifferentiableGradientLayer):
        with torch.no_grad():
            model.log_sigma.fill_(-10.0)
            model.log_gain.fill_(0.0)
            model.bias.fill_(0.0)
            model.shifts.fill_(0.0)
            model.lfields.fill_(0.0)
    for parameter in model.parameters():
        parameter.requires_grad_(False)


def create_forward_model(
    sim_cfg: SimulationConfig,
    train_cfg: TrainingConfig | None = None,
    *,
    device: torch.device | str | None = None,
    freeze: bool = True,
) -> torch.nn.Module:
    """
    Build the differentiable forward model used by physics losses, priors, and QC.

    This is intentionally separate from the offline capture simulator. A future run may
    train on data generated by one capture engine while using a different, weaker, or
    calibrated differentiable model for loss/QC; the chosen model is recorded in config.
    """

    name = "ideal_gradient"
    if train_cfg is not None:
        name = str(getattr(train_cfg, "forward_model", "ideal_gradient") or "ideal_gradient")

    if name in {"ideal_gradient", "legacy"}:
        model: torch.nn.Module = DifferentiableGradientLayer(sim_cfg)
    else:
        raise ValueError(f"Unknown forward_model={name!r}")

    if device is not None:
        model = model.to(device)
    if freeze:
        freeze_forward_model(model)
    return model


def forward_model_meta(train_cfg: TrainingConfig | None = None) -> dict[str, Any]:
    name = "ideal_gradient"
    params: dict[str, Any] = {}
    if train_cfg is not None:
        name = str(getattr(train_cfg, "forward_model", "ideal_gradient") or "ideal_gradient")
        raw_params = getattr(train_cfg, "forward_model_params", {}) or {}
        params = dict(raw_params) if isinstance(raw_params, dict) else {"value": raw_params}
    return {"forward_model": name, "forward_model_params": params}


__all__ = ["create_forward_model", "forward_model_meta", "freeze_forward_model"]
